name: construction_webpage
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter:

 
  uses-material-design: true


  assets:
   - assets/istockphoto.jpg
   - assets/istockphotoor.jpg

  fonts:
  - family: Corben
    fonts: 
     - asset: fonts\AveriaSansLibre-Regular.ttf
    
  - family: Rozha
    fonts:
     - asset: fonts\RozhaOne-Regular.ttf
  
  - family: AveriaSansLibre
    fonts:
     - asset: fonts\AveriaSansLibre-Regular.ttf

  - family: MrsSaintDelafield
    fonts:
     - asset: fonts\MrsSaintDelafield-Regular.ttf
    
       
